# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-03 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0046_update_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=32)),
                ('long_title', models.CharField(max_length=100)),
            ],
        ),
    ]
