# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-03 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0048_seed_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionModerationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.Election')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.ModerationStatus')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='election',
            name='moderation_statuses',
            field=models.ManyToManyField(through='elections.ElectionModerationStatus', to='elections.ModerationStatus'),
        ),
    ]
