# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-03 11:00
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager
import elections.managers


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0049_auto_20181003_1010'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='election',
            managers=[
                ('public_objects', django.db.models.manager.Manager()),
                ('private_objects', elections.managers.PrivateElectionsManager()),
            ],
        ),
    ]
