# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-03 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0051_move_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationstatus',
            name='short_title',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
