# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0053_auto_20181004_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderationstatus',
            old_name='long_title',
            new_name='long_label',
        ),
        migrations.RenameField(
            model_name='moderationstatus',
            old_name='short_title',
            new_name='short_label',
        ),
    ]
