# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0054_auto_20181005_1244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElectionModerationStatus',
            new_name='ModerationHistory',
        ),
    ]
