# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0032_auto_20180531_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_name', models.CharField(blank=True, max_length=255)),
                ('common_name', models.CharField(blank=True, max_length=255)),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('election_name', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='organisations.Organisation')),
            ],
        ),
    ]
