# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0034_copy_orgname_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'ordering': ('official_identifier',)},
        ),
        migrations.AlterModelOptions(
            name='organisationname',
            options={'get_latest_by': 'start_date'},
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='common_name',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='election_name',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='official_name',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='slug',
        ),
        migrations.AlterField(
            model_name='organisationname',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='organisations.Organisation'),
        ),
    ]
